import {
  PetType,
  PetStatus,
  PetSpecies,
  PetGender,
  PetSize,
} from "../pet/petType";

export const PET_LIST_EXAMPLE: PetType[] = [
  {
    id: "1",
    name: "Amendoim",
    specie: PetSpecies.dog,
    gender: PetGender.male,
    age: "1 ano",
    size: PetSize.medium,
    personality: "Brincalhão, curioso e muito carinhoso com crianças.",
    image: "/pet-placeholder-1.jpg",
    status: PetStatus.available,
  },
  {
    id: "2",
    name: "Pipoca",
    specie: PetSpecies.dog,
    gender: PetGender.female,
    age: "3 anos",
    size: PetSize.small,
    personality: "Calma, afetuosa e adora um colo.",
    image: "/pet-placeholder-2.jpg",
    status: PetStatus.available,
  },
  {
    id: "3",
    name: "Mel",
    specie: PetSpecies.cat,
    gender: PetGender.female,
    age: "2 anos",
    size: PetSize.medium,
    personality: "Independente mas muito carinhosa no seu tempo.",
    image: "/pet-placeholder-3.jpg",
    status: PetStatus.available,
  },
  {
    id: "4",
    name: "Biscoito",
    specie: PetSpecies.dog,
    gender: PetGender.male,
    age: "5 meses",
    size: PetSize.small,
    personality: "Filhote energético, adora explorar e brincar.",
    image: "/pet-placeholder-4.jpg",
    status: PetStatus.available,
  },
  {
    id: "5",
    name: "Caju",
    specie: PetSpecies.cat,
    gender: PetGender.male,
    age: "4 anos",
    size: PetSize.big,
    personality: "Tranquilo, gosta de sol e ronrona fácil.",
    image: "/pet-placeholder-5.jpg",
    status: PetStatus.available,
  },
  {
    id: "6",
    name: "Farofa",
    specie: PetSpecies.dog,
    gender: PetGender.female,
    age: "2 anos",
    size: PetSize.big,
    personality: "Amigável com outros animais e ótima companhia para corridas.",
    image: "/pet-placeholder-6.jpg",
    status: PetStatus.available,
  },
];
